Move retry logic higher in the call stack
Previously a retry was attempted only for HTTP error statuses (!=200) and
for connection failures like requests.ConnectionError or requests.Timeout

Turns out GraphQL API of CirrusCI can reply with "Internal server error"
wrapped into a perfectly valid HTTP (200) response:

    https://gitlab.com/libvirt/libvirt/-/jobs/670297678    [1]

Therefore retry logic is now processed higher in the call stack,
in __call__() instead of _post(). Now retries are also triggered for
CirrusAPIErrors.

PS: Unfortunately default diff algorithm produces very confusing output
for this change set, much better diff can be generated by using:

    git show #commit --anchored="    def _parse_api_response"

---

Copy of traceback listing from link [1]:

$ cirrus-run -v --show-build-log always ci/cirrus/$NAME.yml
Traceback (most recent call last):
  File "/usr/bin/cirrus-run", line 11, in <module>
    load_entry_point('cirrus-run==0.2.0', 'console_scripts', 'cirrus-run')()
  File "/usr/lib/python3.6/site-packages/cirrus_run-0.2.0-py3.6.egg/cirrus_run/cli.py", line 40, in main
  File "/usr/lib/python3.6/site-packages/cirrus_run-0.2.0-py3.6.egg/cirrus_run/queries.py", line 84, in create_build
  File "/usr/lib/python3.6/site-packages/cirrus_run-0.2.0-py3.6.egg/cirrus_run/api.py", line 64, in __call__
  File "/usr/lib/python3.6/site-packages/cirrus_run-0.2.0-py3.6.egg/cirrus_run/api.py", line 68, in _parse_api_response
cirrus_run.api.CirrusAPIError: API returned 1 error(s):
[{'message': 'Internal Server Error(s) while executing query'}]